[package]
name = "scenarios"
version = "0.1.0"
authors = ["Nico Madysa <nico.madysa@tu-dresden.de>"]

[dependencies]
regex = "*"
lazy_static = "*"

[dependencies.clap]
version = "*"
features = ["wrap_help"]
