[package]
name = "scenarios"
version = "0.1.0"
authors = ["Nico Madysa <nico.madysa@tu-dresden.de>"]
description = "Run a command line multiple times in different environments."

[dependencies]
num_cpus = "*"
quick-error = "*"
clap = { version = "*", features = ["wrap_help"] }
